// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
import 'package:flutter/cupertino.dart';
import '../app_theme.dart';
import 'rounded_cupertino_sheet.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Emoji category data
// ─────────────────────────────────────────────────────────────────────────────

typedef _EmojiCat = ({String icon, String name, List<String> emojis});

const List<_EmojiCat> kEmojiCategories = [
  (
    icon: '😀',
    name: 'Smileys',
    emojis: [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '🤣',
      '😂',
      '🙂',
      '🙃',
      '😉',
      '😊',
      '😇',
      '🥰',
      '😍',
      '🤩',
      '😘',
      '😗',
      '😚',
      '😙',
      '🥲',
      '😋',
      '😛',
      '😜',
      '🤪',
      '😝',
      '🤑',
      '🤗',
      '🤭',
      '🫢',
      '🤫',
      '🤔',
      '🫡',
      '🤐',
      '🤨',
      '😐',
      '😑',
      '😶',
      '😏',
      '😒',
      '🙄',
      '😬',
      '🤥',
      '😌',
      '😔',
      '😪',
      '🤤',
      '😴',
      '😷',
      '🤒',
      '🤕',
      '🤢',
      '🤮',
      '🤧',
      '🥵',
      '🥶',
      '🥴',
      '😵',
      '🤯',
      '🤠',
      '🥳',
      '🥸',
      '😎',
      '🤓',
      '🧐',
      '😕',
      '😟',
      '🙁',
      '☹️',
      '😮',
      '😯',
      '😲',
      '😳',
      '🥺',
      '😦',
      '😧',
      '😨',
      '😰',
      '😥',
      '😢',
      '😭',
      '😱',
      '😖',
      '😣',
      '😞',
      '😓',
      '😩',
      '😫',
      '🥱',
      '😤',
      '😡',
      '😠',
      '🤬',
      '😈',
      '👿',
      '💀',
      '☠️',
      '💩',
      '🤡',
      '👻',
      '👽',
      '🤖',
      '😺',
      '😸',
      '😹',
      '😻',
      '😼',
      '😽',
      '🙀',
      '😿',
      '😾',
    ],
  ),
  (
    icon: '👋🏻',
    name: 'People',
    emojis: [
      '👋🏻',
      '🤚🏻',
      '🖐🏻',
      '✋🏻',
      '🖖🏻',
      '👌🏻',
      '🤌🏻',
      '🤏🏻',
      '✌🏻',
      '🤞🏻',
      '🤟🏻',
      '🤘🏻',
      '🤙🏻',
      '👈🏻',
      '👉🏻',
      '👆🏻',
      '👇🏻',
      '☝🏻',
      '👍🏻',
      '👎🏻',
      '✊🏻',
      '👊🏻',
      '🤛🏻',
      '🤜🏻',
      '👏🏻',
      '🙌🏻',
      '🫶🏻',
      '👐🏻',
      '🤲🏻',
      '🤝🏻',
      '🙏🏻',
      '💪🏻',
      '🦾',
      '🦵🏻',
      '🦶🏻',
      '👂🏻',
      '🦻🏻',
      '👃🏻',
      '🧠',
      '👀',
      '👅',
      '💋',
      '🧑🏻',
      '👦🏻',
      '👧🏻',
      '👨🏻',
      '👩🏻',
      '🧓🏻',
      '👴🏻',
      '👵🏻',
      '👶🏻',
      '🧒🏻',
      '💆🏻',
      '💇🏻',
      '🚶🏻',
      '🏃🏻',
      '💃🏻',
      '🕺🏻',
      '🧗🏻',
      '🤸🏻',
      '⛹🏻',
      '🏋🏻',
      '🤼',
      '🏄🏻',
      '🚣🏻',
      '🧘🏻',
      '🏊🏻',
      '🚴🏻',
      '🛀🏻',
      '🧖🏻',
      '🧘🏻',
      '👫',
      '👬',
      '👭',
      '👨‍👩‍👦',
      '👨‍👩‍👧',
      '👨‍👩‍👧‍👦',
    ],
  ),
  (
    icon: '🐶',
    name: 'Animals',
    emojis: [
      '🐶',
      '🐱',
      '🐭',
      '🐹',
      '🐰',
      '🦊',
      '🐻',
      '🐼',
      '🐨',
      '🐯',
      '🦁',
      '🐮',
      '🐷',
      '🐸',
      '🐵',
      '🙈',
      '🙉',
      '🙊',
      '🐔',
      '🐧',
      '🐦',
      '🐤',
      '🦆',
      '🦅',
      '🦉',
      '🦇',
      '🐝',
      '🦋',
      '🐛',
      '🐌',
      '🐞',
      '🐜',
      '🕷️',
      '🦂',
      '🐢',
      '🐍',
      '🦎',
      '🦖',
      '🦕',
      '🐙',
      '🦑',
      '🦐',
      '🦀',
      '🐟',
      '🐠',
      '🐡',
      '🐬',
      '🐳',
      '🐋',
      '🦈',
      '🦭',
      '🐊',
      '🐅',
      '🐆',
      '🦓',
      '🐘',
      '🦛',
      '🦏',
      '🐪',
      '🦒',
      '🦘',
      '🦬',
      '🐃',
      '🐄',
      '🐎',
      '🐖',
      '🐑',
      '🦙',
      '🐐',
      '🦌',
      '🐕',
      '🐩',
      '🦮',
      '🐕‍🦺',
      '🐈',
      '🐈‍⬛',
      '🐓',
      '🦃',
      '🦚',
      '🦜',
      '🦢',
      '🕊️',
      '🐇',
      '🦝',
      '🦨',
      '🦡',
      '🦦',
      '🦥',
      '🐁',
      '🐀',
      '🐿️',
      '🦔',
      '🐾',
      '🌸',
      '🌺',
      '🌻',
      '🌹',
      '🌷',
      '🌼',
      '🪷',
      '🌱',
      '🌿',
      '☘️',
      '🍀',
      '🌵',
      '🌲',
      '🌳',
      '🌴',
      '🍄',
      '🌾',
      '💐',
      '☀️',
      '🌤️',
      '⛅',
      '🌦️',
      '🌧️',
      '⛈️',
      '🌩️',
      '🌨️',
      '❄️',
      '⚡',
      '🔥',
      '💧',
      '🌊',
      '🌈',
      '🌙',
      '⭐',
      '🌟',
      '✨',
      '🌠',
    ],
  ),
  (
    icon: '🍎',
    name: 'Food',
    emojis: [
      '🍏',
      '🍎',
      '🍐',
      '🍊',
      '🍋',
      '🍌',
      '🍉',
      '🍇',
      '🍓',
      '🫐',
      '🍒',
      '🍑',
      '🥭',
      '🍍',
      '🥥',
      '🥝',
      '🍅',
      '🫒',
      '🥑',
      '🌽',
      '🥕',
      '🥦',
      '🥬',
      '🌶️',
      '🧄',
      '🧅',
      '🥔',
      '🥜',
      '🫘',
      '🍞',
      '🥐',
      '🥖',
      '🫓',
      '🧀',
      '🥚',
      '🍳',
      '🥞',
      '🧇',
      '🥓',
      '🥩',
      '🍗',
      '🍖',
      '🌭',
      '🍔',
      '🍟',
      '🍕',
      '🌮',
      '🌯',
      '🥗',
      '🍝',
      '🍜',
      '🍲',
      '🍛',
      '🍣',
      '🍱',
      '🥟',
      '🍤',
      '🍙',
      '🍚',
      '🍘',
      '🍥',
      '🧁',
      '🍰',
      '🎂',
      '🍮',
      '🍭',
      '🍬',
      '🍫',
      '🍿',
      '🍩',
      '🍪',
      '🌰',
      '🍯',
      '☕',
      '🫖',
      '🍵',
      '🧃',
      '🥤',
      '🧋',
      '🍺',
      '🍻',
      '🥂',
      '🍷',
      '🥃',
      '🍸',
      '🍹',
      '🧊',
      '🥄',
      '🍴',
      '🍽️',
      '🥢',
      '🧂',
    ],
  ),
  (
    icon: '⚽',
    name: 'Activities',
    emojis: [
      '⚽',
      '🏀',
      '🏈',
      '⚾',
      '🥎',
      '🎾',
      '🏐',
      '🏉',
      '🥏',
      '🎱',
      '🪀',
      '🏓',
      '🏸',
      '🏒',
      '🥊',
      '🥋',
      '🎽',
      '🛹',
      '🛼',
      '🛷',
      '⛸️',
      '🥌',
      '🎿',
      '⛷️',
      '🏂',
      '🪂',
      '🏋️',
      '🤼',
      '🤸',
      '🤺',
      '🏇',
      '⛹️',
      '🤾',
      '🏌️',
      '🏄',
      '🚣',
      '🧘',
      '🏊',
      '🚴',
      '🏆',
      '🥇',
      '🥈',
      '🥉',
      '🏅',
      '🎖️',
      '🎪',
      '🤹',
      '🎭',
      '🎨',
      '🎬',
      '🎰',
      '🎮',
      '🕹️',
      '🎲',
      '🎯',
      '🎳',
      '🎻',
      '🎺',
      '🥁',
      '🎸',
      '🎵',
      '🎶',
      '🎤',
      '🎧',
      '🎷',
      '🎹',
      '🪗',
      '🪘',
      '🪕',
      '🎼',
      '🎋',
      '🎍',
      '🎎',
      '🎏',
      '🎐',
      '🎑',
      '🎃',
      '🎄',
      '🎁',
      '🎀',
      '🎊',
      '🎉',
      '🎗️',
      '🎫',
      '🎟️',
    ],
  ),
  (
    icon: '✈️',
    name: 'Travel',
    emojis: [
      '🚗',
      '🚕',
      '🚙',
      '🚌',
      '🏎️',
      '🚓',
      '🚑',
      '🚒',
      '🚐',
      '🛻',
      '🚚',
      '🚛',
      '🚜',
      '🛴',
      '🚲',
      '🛵',
      '🏍️',
      '🚁',
      '🛸',
      '🚀',
      '✈️',
      '🛩️',
      '🚂',
      '🚆',
      '🚇',
      '🚉',
      '🚊',
      '🚝',
      '🚞',
      '🛳️',
      '⛴️',
      '🚢',
      '🛥️',
      '⛵',
      '🚤',
      '🛶',
      '⚓',
      '🛟',
      '🏔️',
      '⛰️',
      '🌋',
      '🗻',
      '🏕️',
      '🏖️',
      '🏗️',
      '🏘️',
      '🏠',
      '🏡',
      '🏢',
      '🏣',
      '🏤',
      '🏥',
      '🏦',
      '🏨',
      '🏩',
      '🏪',
      '🏫',
      '🏬',
      '🏭',
      '🏯',
      '🏰',
      '💒',
      '🗼',
      '🗽',
      '⛪',
      '🕌',
      '🛕',
      '⛩️',
      '⛲',
      '🌁',
      '🌃',
      '🏙️',
      '🌄',
      '🌅',
      '🌆',
      '🌇',
      '🌉',
      '🗺️',
      '🧭',
      '🌐',
      '🗺️',
      '🏁',
      '🚩',
      '🎌',
      '🏴',
      '🏳️',
    ],
  ),
  (
    icon: '💡',
    name: 'Objects',
    emojis: [
      '⌚',
      '📱',
      '💻',
      '⌨️',
      '🖥️',
      '🖨️',
      '🖱️',
      '💽',
      '💾',
      '💿',
      '📷',
      '📸',
      '📹',
      '🎥',
      '📽️',
      '📞',
      '☎️',
      '📺',
      '📻',
      '🧭',
      '⏰',
      '⏱️',
      '⏲️',
      '🕰️',
      '⌛',
      '⏳',
      '📡',
      '🔋',
      '🔌',
      '💡',
      '🔦',
      '🕯️',
      '🧯',
      '💸',
      '💵',
      '💰',
      '💳',
      '🪙',
      '🔑',
      '🗝️',
      '🔐',
      '🔒',
      '🔓',
      '🔨',
      '🪓',
      '⚒️',
      '🛠️',
      '🔧',
      '🪛',
      '🔩',
      '⚙️',
      '🧲',
      '🪜',
      '🧱',
      '🚪',
      '🛋️',
      '🪑',
      '🚽',
      '🚿',
      '🛁',
      '🧴',
      '🪥',
      '🧷',
      '🧹',
      '🧺',
      '🧻',
      '🧼',
      '🛒',
      '🎒',
      '🧳',
      '👜',
      '👛',
      '👓',
      '🕶️',
      '🧤',
      '🧣',
      '🧦',
      '👒',
      '🎩',
      '🧢',
      '👗',
      '👔',
      '👕',
      '👖',
      '🧥',
      '🥼',
      '🧤',
      '🩱',
      '🩲',
      '🩳',
      '👟',
      '👠',
      '👡',
      '👢',
      '🥾',
      '🥿',
      '🧶',
      '🪡',
      '🪢',
      '✉️',
      '📧',
      '📦',
      '📫',
      '📜',
      '📃',
      '📄',
      '📊',
      '📈',
      '📉',
      '📋',
      '📁',
      '📂',
      '📓',
      '📔',
      '📒',
      '📕',
      '📗',
      '📘',
      '📙',
      '📚',
      '📖',
      '🔖',
      '🏷️',
      '📌',
      '📍',
      '✂️',
      '📏',
      '📐',
      '✒️',
      '🖊️',
      '🖍️',
      '📝',
      '🔍',
      '🔎',
    ],
  ),
  (
    icon: '❤️',
    name: 'Symbols',
    emojis: [
      '❤️',
      '🧡',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '🤎',
      '💔',
      '❤️‍🔥',
      '💕',
      '💞',
      '💓',
      '💗',
      '💖',
      '💘',
      '💝',
      '💟',
      '☮️',
      '✝️',
      '☪️',
      '🕉️',
      '🔯',
      '☸️',
      '🛐',
      '♈',
      '♉',
      '♊',
      '♋',
      '♌',
      '♍',
      '♎',
      '♏',
      '♐',
      '♑',
      '♒',
      '♓',
      '⛎',
      '♻️',
      '✅',
      '☑️',
      '🔱',
      '⚜️',
      '🔰',
      '💯',
      '❌',
      '❓',
      '❗',
      '🔔',
      '🚫',
      '⛔',
      '📣',
      '📢',
      '💬',
      '💭',
      '💤',
      '🎵',
      '🎶',
      '♠️',
      '♣️',
      '♥️',
      '♦️',
      '🃏',
      '🀄',
      '🎴',
      '🔵',
      '🟠',
      '🟡',
      '🟢',
      '🔴',
      '🟣',
      '⚫',
      '⚪',
      '🟤',
      '🔶',
      '🔷',
      '🔸',
      '🔹',
      '🔺',
      '🔻',
      '💠',
      '🔘',
      '🔲',
      '🔳',
      '⬛',
      '⬜',
      '▪️',
      '▫️',
      '◼️',
      '◻️',
      '◾',
      '◽',
    ],
  ),
];

// ─────────────────────────────────────────────────────────────────────────────
// EmojiPickerSheet — full-page sheet content for showRoundedCupertinoSheet
// ─────────────────────────────────────────────────────────────────────────────

class EmojiPickerSheet extends StatefulWidget {
  final ValueChanged<String> onEmojiSelected;
  const EmojiPickerSheet({super.key, required this.onEmojiSelected});

  @override
  State<EmojiPickerSheet> createState() => _EmojiPickerSheetState();
}

class _EmojiPickerSheetState extends State<EmojiPickerSheet> {
  int _catIndex = 0;
  double _dragOffset = 0.0;
  final _scrollCtrl = ScrollController();

  @override
  void dispose() {
    _scrollCtrl.dispose();
    super.dispose();
  }

  void _switchCategory(int i) {
    setState(() {
      _catIndex = i;
      _dragOffset = 0.0;
    });
    _scrollCtrl.jumpTo(0);
  }

  void _onDragUpdate(DragUpdateDetails d, double panelWidth) {
    setState(() {
      double next = _dragOffset + d.delta.dx;
      // Rubber-band resistance at left/right edges
      if ((_catIndex == 0 && next > 0) ||
          (_catIndex == kEmojiCategories.length - 1 && next < 0)) {
        next = next * 0.15;
      }
      _dragOffset = next;
    });
  }

  void _onDragEnd(DragEndDetails d, double panelWidth) {
    final vel = d.primaryVelocity ?? 0;
    final threshold = panelWidth / 2;

    if ((_dragOffset < -threshold || vel < -400) &&
        _catIndex < kEmojiCategories.length - 1) {
      setState(() {
        _catIndex++;
        _dragOffset = 0;
      });
      _scrollCtrl.jumpTo(0);
    } else if ((_dragOffset > threshold || vel > 400) && _catIndex > 0) {
      setState(() {
        _catIndex--;
        _dragOffset = 0;
      });
      _scrollCtrl.jumpTo(0);
    } else {
      setState(() => _dragOffset = 0);
    }
  }

  // Builds the emoji grid for a given category index.
  // Only the active grid is tappable; peeking grids are visual only.
  Widget _buildGrid(int idx, {bool active = false}) {
    final emojis = kEmojiCategories[idx].emojis;
    return GridView.builder(
      controller: active ? _scrollCtrl : null,
      physics: active
          ? const BouncingScrollPhysics(
              decelerationRate: ScrollDecelerationRate.fast,
              parent: AlwaysScrollableScrollPhysics(),
            )
          : const NeverScrollableScrollPhysics(),
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 6),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 8,
        mainAxisSpacing: 2,
        crossAxisSpacing: 2,
      ),
      itemCount: emojis.length,
      itemBuilder: (_, i) {
        if (!active) {
          return Center(
            child: Text(
              emojis[i],
              style: const TextStyle(fontSize: 26, height: 1.0),
            ),
          );
        }
        return CupertinoButton(
          padding: EdgeInsets.zero,
          onPressed: () {
            _close();
            widget.onEmojiSelected(emojis[i]);
          },
          child: Text(
            emojis[i],
            style: const TextStyle(fontSize: 26, height: 1.0),
          ),
        );
      },
    );
  }

  void _close() => Navigator.of(context, rootNavigator: true).pop();

  @override
  Widget build(BuildContext context) {
    final isDark = CupertinoTheme.brightnessOf(context) == Brightness.dark;
    final sepLineColor = kSeparatorColor.resolveFrom(context);
    final labelColor = kPrimaryLabel.resolveFrom(context);
    final cardColor = resolveThemeColor(kModalCard, context);
    final shadows = resolveThemeShadows(kCardShadow, context);

    // Back chevron — replaces xmark in sub-sheets to indicate navigation back.
    // Uses chevron_left to match the DCV header back indicator.
    const _xIcon = CupertinoIcons.chevron_left;
    final _xFamily = _xIcon.fontPackage != null
        ? 'packages/${_xIcon.fontPackage}/${_xIcon.fontFamily}'
        : (_xIcon.fontFamily ?? '');
    final xBtn = GelBloomButton(
      peakScale: 1.15,
      tapDelay: const Duration(milliseconds: 130),
      onTap: _close,
      child: Container(
        width: 40,
        height: 40,
        decoration: ShapeDecoration(
          color: cardColor,
          shape: const CircleBorder(),
          shadows: shadows,
        ),
        child: Center(
          child: SizedBox(
            width: 20,
            height: 20,
            child: Center(
              child: Transform.translate(
                offset: const Offset(-1.5, 0),
                child: RichText(
                  textHeightBehavior: const TextHeightBehavior(
                    applyHeightToFirstAscent: false,
                    applyHeightToLastDescent: false,
                  ),
                  text: TextSpan(
                    text: String.fromCharCode(_xIcon.codePoint),
                    style: TextStyle(
                      inherit: false,
                      color: labelColor,
                      fontSize: 20,
                      fontFamily: _xFamily,
                      fontStyle: FontStyle.normal,
                      shadows: resolveThemeTextShadows([
                        Shadow(color: labelColor, blurRadius: 1.0),
                      ], context),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );

    return CupertinoPageScaffold(
      backgroundColor: kModalBackground,
      child: Column(
        children: [
          // ── Navigation bar ───────────────────────────────────────────────
          RoundedCupertinoSheetHeader(
            child: SizedBox(
              height: 64,
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Row(
                  children: [
                    xBtn,
                    Expanded(
                      child: Center(
                        child: Text(
                          'Choose Emoji',
                          style: TextStyle(
                            inherit: false,
                            color: kPrimaryLabel,
                            fontFamily: kSFProText,
                            fontSize: 17,
                            fontWeight: FontWeight.w600,
                            height: 1.0,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(
                      width: 40,
                    ), // mirrors xBtn width for symmetry
                  ],
                ),
              ),
            ),
          ),
          // ── Card: grid (row 1) + separator + category strip (row 2) ─────
          Expanded(
            child: CustomScrollView(
              physics: const BouncingScrollPhysics(
                parent: AlwaysScrollableScrollPhysics(),
              ),
              slivers: [
                SliverPadding(
                  padding: EdgeInsets.only(
                    bottom: MediaQuery.paddingOf(context).bottom,
                  ),
                  sliver: SliverFillRemaining(
                    hasScrollBody: false,
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 8, 16, 20),
                      child: Container(
                        decoration: ShapeDecoration(
                          color: kModalCard.resolveFrom(context),
                          shape: BoundedContinuousRectangleBorder(
                            borderRadius: BorderRadius.circular(
                              kCardCornerRadius,
                            ),
                          ),
                          shadows: resolveThemeShadows(kCardShadow, context),
                        ),
                        clipBehavior: Clip.antiAlias,
                        child: Column(
                          children: [
                            // Row 1 — swipeable emoji grid
                            Expanded(
                              child: LayoutBuilder(
                                builder: (context, constraints) {
                                  final w = constraints.maxWidth;
                                  return GestureDetector(
                                    behavior: HitTestBehavior.opaque,
                                    onHorizontalDragUpdate: (d) =>
                                        _onDragUpdate(d, w),
                                    onHorizontalDragEnd: (d) =>
                                        _onDragEnd(d, w),
                                    child: Stack(
                                      clipBehavior: Clip.hardEdge,
                                      children: [
                                        if (_catIndex > 0)
                                          Transform.translate(
                                            offset: Offset(_dragOffset - w, 0),
                                            child: _buildGrid(_catIndex - 1),
                                          ),
                                        Transform.translate(
                                          offset: Offset(_dragOffset, 0),
                                          child: _buildGrid(
                                            _catIndex,
                                            active: true,
                                          ),
                                        ),
                                        if (_catIndex <
                                            kEmojiCategories.length - 1)
                                          Transform.translate(
                                            offset: Offset(_dragOffset + w, 0),
                                            child: _buildGrid(_catIndex + 1),
                                          ),
                                      ],
                                    ),
                                  );
                                },
                              ),
                            ),
                            // Separator between the two rows
                            Container(height: 0.5, color: sepLineColor),
                            // Row 2 — category strip
                            SizedBox(
                              height: 52,
                              child: Row(
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceAround,
                                children: List.generate(
                                  kEmojiCategories.length,
                                  (i) {
                                    final sel = i == _catIndex;
                                    return GestureDetector(
                                      onTap: () => _switchCategory(i),
                                      behavior: HitTestBehavior.opaque,
                                      child: Padding(
                                        padding: const EdgeInsets.symmetric(
                                          horizontal: 4,
                                          vertical: 8,
                                        ),
                                        child: Text(
                                          kEmojiCategories[i].icon,
                                          style: TextStyle(
                                            fontSize: sel ? 24.0 : 20.0,
                                            height: 1.0,
                                            color: sel
                                                ? null
                                                : const Color(0x66000000),
                                          ),
                                        ),
                                      ),
                                    );
                                  },
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
